import type { Model, ModelsResponse } from "~/services/copilot/get-models"

type CloudGptModelKind = "chat" | "embeddings" | "image" | "video"
type CloudGptInputModality = "image" | "pdf" | "text" | "video"

interface CloudGptModelDefinition {
  contextWindow: number
  endpoints: Array<string>
  family: string
  id: string
  input: Array<CloudGptInputModality>
  kind: CloudGptModelKind
  maxOutputTokens: number
  modelPickerEnabled?: boolean
  name: string
  parallelToolCalls?: boolean
  preview?: boolean
  reasoningEffort?: Array<string>
  structuredOutputs?: boolean
  tokenizer?: string
  toolCalls?: boolean
  vendor: string
  version?: string
}

const CHAT_COMPLETIONS_ENDPOINT = "/v1/chat/completions"
const RESPONSES_ENDPOINT = "/v1/responses"
const EMBEDDINGS_ENDPOINT = "/v1/embeddings"
const IMAGE_GENERATIONS_ENDPOINT = "/v1/images/generations"
const IMAGE_EDITS_ENDPOINT = "/v1/images/edits"
const VIDEOS_ENDPOINT = "/v1/videos"

const CHAT_AND_RESPONSES = [CHAT_COMPLETIONS_ENDPOINT, RESPONSES_ENDPOINT]
const RESPONSES_ONLY = [RESPONSES_ENDPOINT]
const CHAT_COMPLETIONS_ONLY = [CHAT_COMPLETIONS_ENDPOINT]
const IMAGE_GENERATION_AND_EDIT = [
  IMAGE_GENERATIONS_ENDPOINT,
  IMAGE_EDITS_ENDPOINT,
]

const TEXT_INPUT: Array<CloudGptInputModality> = ["text"]
const TEXT_IMAGE_INPUT: Array<CloudGptInputModality> = ["text", "image"]
const TEXT_IMAGE_PDF_INPUT: Array<CloudGptInputModality> = [
  "text",
  "image",
  "pdf",
]
const TEXT_IMAGE_VIDEO_INPUT: Array<CloudGptInputModality> = [
  "text",
  "image",
  "video",
]

const GPT5_REASONING_EFFORTS = ["minimal", "low", "medium", "high"]
const GPT5_ADVANCED_REASONING_EFFORTS = [
  "none",
  "low",
  "medium",
  "high",
  "xhigh",
]
const CODEX_REASONING_EFFORTS = ["low", "medium", "high"]
const O_SERIES_REASONING_EFFORTS = ["low", "medium", "high"]

export const CLOUDGPT_MODEL_CATALOG = [
  {
    id: "gpt-4o-20240513",
    name: "GPT-4o (2024-05-13)",
    vendor: "openai",
    family: "gpt",
    kind: "chat",
    contextWindow: 128_000,
    maxOutputTokens: 4_096,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-4o-20240806",
    name: "GPT-4o (2024-08-06)",
    vendor: "openai",
    family: "gpt",
    kind: "chat",
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-4o-20241120",
    name: "GPT-4o (2024-11-20)",
    vendor: "openai",
    family: "gpt",
    kind: "chat",
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-4o-mini-20240718",
    name: "GPT-4o mini",
    vendor: "openai",
    family: "gpt-mini",
    kind: "chat",
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-4.1-20250414",
    name: "GPT-4.1",
    vendor: "openai",
    family: "gpt",
    kind: "chat",
    contextWindow: 1_047_576,
    maxOutputTokens: 32_768,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-4.1-mini-20250414",
    name: "GPT-4.1 mini",
    vendor: "openai",
    family: "gpt-mini",
    kind: "chat",
    contextWindow: 1_047_576,
    maxOutputTokens: 32_768,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-4.1-nano-20250414",
    name: "GPT-4.1 nano",
    vendor: "openai",
    family: "gpt-nano",
    kind: "chat",
    contextWindow: 1_047_576,
    maxOutputTokens: 32_768,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-5-20250807",
    name: "GPT-5",
    vendor: "openai",
    family: "gpt",
    kind: "chat",
    contextWindow: 272_000,
    maxOutputTokens: 128_000,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    reasoningEffort: GPT5_REASONING_EFFORTS,
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-5-mini-20250807",
    name: "GPT-5 mini",
    vendor: "openai",
    family: "gpt-mini",
    kind: "chat",
    contextWindow: 272_000,
    maxOutputTokens: 128_000,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    reasoningEffort: GPT5_REASONING_EFFORTS,
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-5-nano-20250807",
    name: "GPT-5 nano",
    vendor: "openai",
    family: "gpt-nano",
    kind: "chat",
    contextWindow: 272_000,
    maxOutputTokens: 128_000,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    reasoningEffort: GPT5_REASONING_EFFORTS,
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-5-pro-20251006",
    name: "GPT-5 Pro",
    vendor: "openai",
    family: "gpt-pro",
    kind: "chat",
    contextWindow: 400_000,
    maxOutputTokens: 272_000,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    reasoningEffort: ["high"],
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-5.1-20251113",
    name: "GPT-5.1",
    vendor: "openai",
    family: "gpt",
    kind: "chat",
    contextWindow: 272_000,
    maxOutputTokens: 128_000,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    reasoningEffort: ["none", "low", "medium", "high"],
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-5.2-20251211",
    name: "GPT-5.2",
    vendor: "openai",
    family: "gpt",
    kind: "chat",
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    reasoningEffort: GPT5_ADVANCED_REASONING_EFFORTS,
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-5.4-20260305",
    name: "GPT-5.4",
    vendor: "openai",
    family: "gpt",
    kind: "chat",
    contextWindow: 1_050_000,
    maxOutputTokens: 128_000,
    input: TEXT_IMAGE_PDF_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    reasoningEffort: GPT5_ADVANCED_REASONING_EFFORTS,
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-5.4-pro-20260305",
    name: "GPT-5.4 Pro",
    vendor: "openai",
    family: "gpt-pro",
    kind: "chat",
    contextWindow: 1_050_000,
    maxOutputTokens: 128_000,
    input: TEXT_IMAGE_INPUT,
    endpoints: RESPONSES_ONLY,
    reasoningEffort: ["medium", "high", "xhigh"],
    toolCalls: true,
  },
  {
    id: "gpt-5.4-mini-20260317",
    name: "GPT-5.4 mini",
    vendor: "openai",
    family: "gpt-mini",
    kind: "chat",
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    input: TEXT_IMAGE_PDF_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    reasoningEffort: GPT5_ADVANCED_REASONING_EFFORTS,
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-5.4-nano-20260317",
    name: "GPT-5.4 nano",
    vendor: "openai",
    family: "gpt-nano",
    kind: "chat",
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    input: TEXT_IMAGE_PDF_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    reasoningEffort: GPT5_ADVANCED_REASONING_EFFORTS,
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-5.5-20260424",
    name: "GPT-5.5",
    vendor: "openai",
    family: "gpt",
    kind: "chat",
    contextWindow: 1_050_000,
    maxOutputTokens: 128_000,
    input: TEXT_IMAGE_PDF_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    reasoningEffort: GPT5_ADVANCED_REASONING_EFFORTS,
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-5.6-sol-20260709",
    name: "GPT-5.6 Sol",
    vendor: "openai",
    family: "gpt",
    kind: "chat",
    contextWindow: 272_000,
    maxOutputTokens: 128_000,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    reasoningEffort: GPT5_ADVANCED_REASONING_EFFORTS,
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-5.6-terra-20260709",
    name: "GPT-5.6 Terra",
    vendor: "openai",
    family: "gpt",
    kind: "chat",
    contextWindow: 272_000,
    maxOutputTokens: 128_000,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    reasoningEffort: GPT5_ADVANCED_REASONING_EFFORTS,
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-5.6-luna-20260709",
    name: "GPT-5.6 Luna",
    vendor: "openai",
    family: "gpt",
    kind: "chat",
    contextWindow: 272_000,
    maxOutputTokens: 128_000,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    reasoningEffort: GPT5_ADVANCED_REASONING_EFFORTS,
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-5-chat-20250807",
    name: "GPT-5 Chat",
    vendor: "openai",
    family: "gpt-chat",
    kind: "chat",
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    toolCalls: false,
    structuredOutputs: true,
  },
  {
    id: "gpt-5-chat-20251003",
    name: "GPT-5 Chat (2025-10-03)",
    vendor: "openai",
    family: "gpt-chat",
    kind: "chat",
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    toolCalls: false,
    structuredOutputs: true,
  },
  {
    id: "gpt-5.1-chat-20251113",
    name: "GPT-5.1 Chat",
    vendor: "openai",
    family: "gpt-chat",
    kind: "chat",
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    reasoningEffort: ["medium"],
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-5.2-chat-20251211",
    name: "GPT-5.2 Chat",
    vendor: "openai",
    family: "gpt-chat",
    kind: "chat",
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    reasoningEffort: ["medium"],
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-5.2-chat-20260210",
    name: "GPT-5.2 Chat (2026-02-10)",
    vendor: "openai",
    family: "gpt-chat",
    kind: "chat",
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    reasoningEffort: ["medium"],
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-5.3-chat-20260303",
    name: "GPT-5.3 Chat",
    vendor: "openai",
    family: "gpt-chat",
    kind: "chat",
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    reasoningEffort: ["medium"],
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-chat-latest-20260505",
    name: "GPT Chat Latest",
    vendor: "openai",
    family: "gpt-chat",
    kind: "chat",
    contextWindow: 128_000,
    maxOutputTokens: 16_384,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    reasoningEffort: ["medium"],
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "codex-mini-20250516",
    name: "Codex Mini",
    vendor: "openai",
    family: "gpt-codex-mini",
    kind: "chat",
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    input: TEXT_INPUT,
    endpoints: RESPONSES_ONLY,
    reasoningEffort: CODEX_REASONING_EFFORTS,
    toolCalls: true,
  },
  {
    id: "gpt-5-codex-20250915",
    name: "GPT-5 Codex",
    vendor: "openai",
    family: "gpt-codex",
    kind: "chat",
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    input: TEXT_IMAGE_INPUT,
    endpoints: RESPONSES_ONLY,
    reasoningEffort: CODEX_REASONING_EFFORTS,
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-5.1-codex-20251113",
    name: "GPT-5.1 Codex",
    vendor: "openai",
    family: "gpt-codex",
    kind: "chat",
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    input: TEXT_IMAGE_INPUT,
    endpoints: RESPONSES_ONLY,
    reasoningEffort: CODEX_REASONING_EFFORTS,
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-5.1-codex-mini-20251113",
    name: "GPT-5.1 Codex mini",
    vendor: "openai",
    family: "gpt-codex",
    kind: "chat",
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    input: TEXT_IMAGE_INPUT,
    endpoints: RESPONSES_ONLY,
    reasoningEffort: CODEX_REASONING_EFFORTS,
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-5.1-codex-max-20251204",
    name: "GPT-5.1 Codex Max",
    vendor: "openai",
    family: "gpt-codex",
    kind: "chat",
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    input: TEXT_IMAGE_INPUT,
    endpoints: RESPONSES_ONLY,
    reasoningEffort: ["low", "medium", "high", "xhigh"],
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-5.2-codex-20260114",
    name: "GPT-5.2 Codex",
    vendor: "openai",
    family: "gpt-codex",
    kind: "chat",
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    input: TEXT_IMAGE_INPUT,
    endpoints: RESPONSES_ONLY,
    reasoningEffort: ["low", "medium", "high", "xhigh"],
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "gpt-5.3-codex-20260224",
    name: "GPT-5.3 Codex",
    vendor: "openai",
    family: "gpt-codex",
    kind: "chat",
    contextWindow: 400_000,
    maxOutputTokens: 128_000,
    input: TEXT_IMAGE_INPUT,
    endpoints: RESPONSES_ONLY,
    reasoningEffort: GPT5_ADVANCED_REASONING_EFFORTS,
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "computer-use-preview-20250311",
    name: "Computer Use Preview",
    vendor: "openai",
    family: "computer-use",
    kind: "chat",
    contextWindow: 8_192,
    maxOutputTokens: 1_024,
    input: TEXT_IMAGE_INPUT,
    endpoints: RESPONSES_ONLY,
    preview: true,
    toolCalls: true,
    modelPickerEnabled: false,
  },
  {
    id: "o1-20241217",
    name: "o1",
    vendor: "openai",
    family: "o",
    kind: "chat",
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    reasoningEffort: O_SERIES_REASONING_EFFORTS,
    toolCalls: true,
  },
  {
    id: "o3-mini-20250131",
    name: "o3-mini",
    vendor: "openai",
    family: "o-mini",
    kind: "chat",
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    input: TEXT_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    reasoningEffort: O_SERIES_REASONING_EFFORTS,
    toolCalls: true,
  },
  {
    id: "o3-20250416",
    name: "o3",
    vendor: "openai",
    family: "o",
    kind: "chat",
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    reasoningEffort: O_SERIES_REASONING_EFFORTS,
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "o3-pro-20250610",
    name: "o3-pro",
    vendor: "openai",
    family: "o-pro",
    kind: "chat",
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    input: TEXT_IMAGE_INPUT,
    endpoints: RESPONSES_ONLY,
    reasoningEffort: O_SERIES_REASONING_EFFORTS,
    toolCalls: true,
  },
  {
    id: "o3-deep-research-20250626",
    name: "o3 Deep Research",
    vendor: "openai",
    family: "o-deep-research",
    kind: "chat",
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    input: TEXT_INPUT,
    endpoints: RESPONSES_ONLY,
    reasoningEffort: O_SERIES_REASONING_EFFORTS,
    toolCalls: true,
  },
  {
    id: "o4-mini-20250416",
    name: "o4-mini",
    vendor: "openai",
    family: "o-mini",
    kind: "chat",
    contextWindow: 200_000,
    maxOutputTokens: 100_000,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_AND_RESPONSES,
    reasoningEffort: O_SERIES_REASONING_EFFORTS,
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "text-embedding-ada-002",
    name: "text-embedding-ada-002",
    vendor: "openai",
    family: "embedding",
    kind: "embeddings",
    contextWindow: 60_000,
    maxOutputTokens: 1_500,
    input: TEXT_INPUT,
    endpoints: [EMBEDDINGS_ENDPOINT],
    modelPickerEnabled: false,
  },
  {
    id: "text-embedding-3-small",
    name: "text-embedding-3-small",
    vendor: "openai",
    family: "embedding",
    kind: "embeddings",
    contextWindow: 32_000,
    maxOutputTokens: 1_024,
    input: TEXT_INPUT,
    endpoints: [EMBEDDINGS_ENDPOINT],
    modelPickerEnabled: false,
  },
  {
    id: "text-embedding-3-large",
    name: "text-embedding-3-large",
    vendor: "openai",
    family: "embedding",
    kind: "embeddings",
    contextWindow: 64_000,
    maxOutputTokens: 2_048,
    input: TEXT_INPUT,
    endpoints: [EMBEDDINGS_ENDPOINT],
    modelPickerEnabled: false,
  },
  {
    id: "gpt-oss-20b",
    name: "GPT-OSS 20B",
    vendor: "openai",
    family: "gpt-oss",
    kind: "chat",
    contextWindow: 131_072,
    maxOutputTokens: 32_768,
    input: TEXT_INPUT,
    endpoints: CHAT_COMPLETIONS_ONLY,
    reasoningEffort: ["low", "medium", "high"],
    toolCalls: true,
  },
  {
    id: "gpt-oss-120b",
    name: "GPT-OSS 120B",
    vendor: "openai",
    family: "gpt-oss",
    kind: "chat",
    contextWindow: 131_072,
    maxOutputTokens: 32_768,
    input: TEXT_INPUT,
    endpoints: CHAT_COMPLETIONS_ONLY,
    reasoningEffort: ["low", "medium", "high"],
    toolCalls: true,
  },
  {
    id: "grok-3",
    name: "Grok 3",
    vendor: "xai",
    family: "grok",
    kind: "chat",
    contextWindow: 131_072,
    maxOutputTokens: 131_072,
    input: TEXT_INPUT,
    endpoints: CHAT_COMPLETIONS_ONLY,
    toolCalls: true,
  },
  {
    id: "grok-3-mini",
    name: "Grok 3 Mini",
    vendor: "xai",
    family: "grok",
    kind: "chat",
    contextWindow: 131_072,
    maxOutputTokens: 131_072,
    input: TEXT_INPUT,
    endpoints: CHAT_COMPLETIONS_ONLY,
    reasoningEffort: O_SERIES_REASONING_EFFORTS,
    toolCalls: true,
  },
  {
    id: "grok-4",
    name: "Grok 4",
    vendor: "xai",
    family: "grok",
    kind: "chat",
    contextWindow: 256_000,
    maxOutputTokens: 30_000,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_COMPLETIONS_ONLY,
    reasoningEffort: ["none", "low", "medium", "high"],
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "grok-4-fast-reasoning",
    name: "Grok 4 Fast (Reasoning)",
    vendor: "xai",
    family: "grok",
    kind: "chat",
    contextWindow: 2_000_000,
    maxOutputTokens: 30_000,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_COMPLETIONS_ONLY,
    reasoningEffort: O_SERIES_REASONING_EFFORTS,
    toolCalls: true,
  },
  {
    id: "grok-4-fast-non-reasoning",
    name: "Grok 4 Fast (Non-Reasoning)",
    vendor: "xai",
    family: "grok",
    kind: "chat",
    contextWindow: 2_000_000,
    maxOutputTokens: 30_000,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_COMPLETIONS_ONLY,
    toolCalls: true,
  },
  {
    id: "grok-code-fast-1",
    name: "Grok Code Fast 1",
    vendor: "xai",
    family: "grok-code",
    kind: "chat",
    contextWindow: 256_000,
    maxOutputTokens: 10_000,
    input: TEXT_INPUT,
    endpoints: CHAT_COMPLETIONS_ONLY,
    toolCalls: true,
  },
  {
    id: "grok-4-1-fast-reasoning",
    name: "Grok 4.1 Fast (Reasoning)",
    vendor: "xai",
    family: "grok",
    kind: "chat",
    contextWindow: 128_000,
    maxOutputTokens: 8_192,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_COMPLETIONS_ONLY,
    reasoningEffort: O_SERIES_REASONING_EFFORTS,
    toolCalls: true,
  },
  {
    id: "grok-4-1-fast-non-reasoning",
    name: "Grok 4.1 Fast (Non-Reasoning)",
    vendor: "xai",
    family: "grok",
    kind: "chat",
    contextWindow: 128_000,
    maxOutputTokens: 8_192,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_COMPLETIONS_ONLY,
    toolCalls: true,
  },
  {
    id: "grok-4-20-reasoning",
    name: "Grok 4.20 (Reasoning)",
    vendor: "xai",
    family: "grok",
    kind: "chat",
    contextWindow: 262_000,
    maxOutputTokens: 8_192,
    input: TEXT_INPUT,
    endpoints: CHAT_COMPLETIONS_ONLY,
    reasoningEffort: O_SERIES_REASONING_EFFORTS,
    toolCalls: true,
  },
  {
    id: "grok-4-20-non-reasoning",
    name: "Grok 4.20 (Non-Reasoning)",
    vendor: "xai",
    family: "grok",
    kind: "chat",
    contextWindow: 262_000,
    maxOutputTokens: 8_192,
    input: TEXT_INPUT,
    endpoints: CHAT_COMPLETIONS_ONLY,
    toolCalls: true,
  },
  {
    id: "grok-4.3",
    name: "Grok 4.3",
    vendor: "xai",
    family: "grok",
    kind: "chat",
    contextWindow: 1_000_000,
    maxOutputTokens: 30_000,
    input: TEXT_IMAGE_PDF_INPUT,
    endpoints: CHAT_COMPLETIONS_ONLY,
    reasoningEffort: ["none", "low", "medium", "high"],
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "DeepSeek-V3-0324",
    name: "DeepSeek V3 0324",
    vendor: "deepseek",
    family: "deepseek",
    kind: "chat",
    contextWindow: 131_072,
    maxOutputTokens: 131_072,
    input: TEXT_INPUT,
    endpoints: CHAT_COMPLETIONS_ONLY,
    toolCalls: true,
  },
  {
    id: "DeepSeek-R1",
    name: "DeepSeek R1",
    vendor: "deepseek",
    family: "deepseek-thinking",
    kind: "chat",
    contextWindow: 163_840,
    maxOutputTokens: 163_840,
    input: TEXT_INPUT,
    endpoints: CHAT_COMPLETIONS_ONLY,
    reasoningEffort: [],
    toolCalls: false,
  },
  {
    id: "DeepSeek-R1-0528",
    name: "DeepSeek R1 0528",
    vendor: "deepseek",
    family: "deepseek-thinking",
    kind: "chat",
    contextWindow: 163_840,
    maxOutputTokens: 163_840,
    input: TEXT_INPUT,
    endpoints: CHAT_COMPLETIONS_ONLY,
    reasoningEffort: [],
    toolCalls: true,
  },
  {
    id: "DeepSeek-V3.1",
    name: "DeepSeek V3.1",
    vendor: "deepseek",
    family: "deepseek",
    kind: "chat",
    contextWindow: 131_072,
    maxOutputTokens: 131_072,
    input: TEXT_INPUT,
    endpoints: CHAT_COMPLETIONS_ONLY,
    reasoningEffort: [],
    toolCalls: true,
  },
  {
    id: "DeepSeek-V3.2",
    name: "DeepSeek V3.2",
    vendor: "deepseek",
    family: "deepseek",
    kind: "chat",
    contextWindow: 128_000,
    maxOutputTokens: 128_000,
    input: TEXT_INPUT,
    endpoints: CHAT_COMPLETIONS_ONLY,
    reasoningEffort: [],
    toolCalls: true,
  },
  {
    id: "DeepSeek-V3.2-Speciale",
    name: "DeepSeek V3.2 Speciale",
    vendor: "deepseek",
    family: "deepseek",
    kind: "chat",
    contextWindow: 128_000,
    maxOutputTokens: 128_000,
    input: TEXT_INPUT,
    endpoints: CHAT_COMPLETIONS_ONLY,
    reasoningEffort: [],
    toolCalls: false,
  },
  {
    id: "DeepSeek-V4-Flash",
    name: "DeepSeek V4 Flash",
    vendor: "deepseek",
    family: "deepseek-flash",
    kind: "chat",
    contextWindow: 1_000_000,
    maxOutputTokens: 384_000,
    input: TEXT_INPUT,
    endpoints: CHAT_COMPLETIONS_ONLY,
    reasoningEffort: [],
    toolCalls: false,
    structuredOutputs: true,
  },
  {
    id: "DeepSeek-V4-Pro",
    name: "DeepSeek V4 Pro",
    vendor: "deepseek",
    family: "deepseek-thinking",
    kind: "chat",
    contextWindow: 1_000_000,
    maxOutputTokens: 384_000,
    input: TEXT_INPUT,
    endpoints: CHAT_COMPLETIONS_ONLY,
    reasoningEffort: [],
    toolCalls: false,
    structuredOutputs: true,
  },
  {
    id: "Kimi-K2-Thinking",
    name: "Kimi K2 Thinking",
    vendor: "moonshot",
    family: "kimi-thinking",
    kind: "chat",
    contextWindow: 262_144,
    maxOutputTokens: 262_144,
    input: TEXT_INPUT,
    endpoints: CHAT_COMPLETIONS_ONLY,
    reasoningEffort: [],
    toolCalls: true,
  },
  {
    id: "Kimi-K2.5",
    name: "Kimi K2.5",
    vendor: "moonshot",
    family: "kimi-k2",
    kind: "chat",
    contextWindow: 262_144,
    maxOutputTokens: 262_144,
    input: TEXT_IMAGE_VIDEO_INPUT,
    endpoints: CHAT_COMPLETIONS_ONLY,
    reasoningEffort: [],
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "Kimi-K2.6",
    name: "Kimi K2.6",
    vendor: "moonshot",
    family: "kimi-k2",
    kind: "chat",
    contextWindow: 262_144,
    maxOutputTokens: 262_144,
    input: TEXT_IMAGE_VIDEO_INPUT,
    endpoints: CHAT_COMPLETIONS_ONLY,
    reasoningEffort: [],
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "Kimi-K2.7-Code",
    name: "Kimi K2.7 Code",
    vendor: "moonshot",
    family: "kimi-k2",
    kind: "chat",
    contextWindow: 262_144,
    maxOutputTokens: 262_144,
    input: TEXT_IMAGE_VIDEO_INPUT,
    endpoints: CHAT_COMPLETIONS_ONLY,
    reasoningEffort: [],
    toolCalls: true,
    structuredOutputs: true,
  },
  {
    id: "Llama-3.3-70B-Instruct",
    name: "Llama 3.3 70B Instruct",
    vendor: "meta",
    family: "llama",
    kind: "chat",
    contextWindow: 128_000,
    maxOutputTokens: 32_768,
    input: TEXT_INPUT,
    endpoints: CHAT_COMPLETIONS_ONLY,
    toolCalls: true,
  },
  {
    id: "Llama-4-Maverick-17B-128E-Instruct-FP8",
    name: "Llama 4 Maverick 17B 128E Instruct FP8",
    vendor: "meta",
    family: "llama",
    kind: "chat",
    contextWindow: 128_000,
    maxOutputTokens: 8_192,
    input: TEXT_IMAGE_INPUT,
    endpoints: CHAT_COMPLETIONS_ONLY,
    toolCalls: true,
  },
  {
    id: "gpt-image-1",
    name: "GPT-Image-1",
    vendor: "openai",
    family: "gpt-image",
    kind: "image",
    contextWindow: 0,
    maxOutputTokens: 0,
    input: TEXT_IMAGE_INPUT,
    endpoints: IMAGE_GENERATION_AND_EDIT,
    modelPickerEnabled: false,
  },
  {
    id: "gpt-image-1-mini",
    name: "GPT-Image-1 mini",
    vendor: "openai",
    family: "gpt-image",
    kind: "image",
    contextWindow: 0,
    maxOutputTokens: 0,
    input: TEXT_IMAGE_INPUT,
    endpoints: IMAGE_GENERATION_AND_EDIT,
    modelPickerEnabled: false,
  },
  {
    id: "gpt-image-1.5",
    name: "GPT-Image-1.5",
    vendor: "openai",
    family: "gpt-image",
    kind: "image",
    contextWindow: 0,
    maxOutputTokens: 0,
    input: TEXT_IMAGE_INPUT,
    endpoints: IMAGE_GENERATION_AND_EDIT,
    modelPickerEnabled: false,
  },
  {
    id: "gpt-image-2",
    name: "GPT-Image-2",
    vendor: "openai",
    family: "gpt-image",
    kind: "image",
    contextWindow: 0,
    maxOutputTokens: 0,
    input: TEXT_IMAGE_INPUT,
    endpoints: IMAGE_GENERATION_AND_EDIT,
    modelPickerEnabled: false,
  },
  {
    id: "MAI-Image-2",
    name: "MAI Image 2",
    vendor: "microsoft",
    family: "mai-image",
    kind: "image",
    contextWindow: 0,
    maxOutputTokens: 0,
    input: TEXT_IMAGE_INPUT,
    endpoints: [IMAGE_GENERATIONS_ENDPOINT],
    modelPickerEnabled: false,
  },
  {
    id: "MAI-Image-2e",
    name: "MAI Image 2e",
    vendor: "microsoft",
    family: "mai-image",
    kind: "image",
    contextWindow: 0,
    maxOutputTokens: 0,
    input: TEXT_IMAGE_INPUT,
    endpoints: [IMAGE_GENERATIONS_ENDPOINT],
    modelPickerEnabled: false,
  },
  {
    id: "MAI-Image-2.5",
    name: "MAI Image 2.5",
    vendor: "microsoft",
    family: "mai-image",
    kind: "image",
    contextWindow: 0,
    maxOutputTokens: 0,
    input: TEXT_IMAGE_INPUT,
    endpoints: [IMAGE_GENERATIONS_ENDPOINT],
    modelPickerEnabled: false,
  },
  {
    id: "MAI-Image-2.5-Flash",
    name: "MAI Image 2.5 Flash",
    vendor: "microsoft",
    family: "mai-image",
    kind: "image",
    contextWindow: 0,
    maxOutputTokens: 0,
    input: TEXT_IMAGE_INPUT,
    endpoints: [IMAGE_GENERATIONS_ENDPOINT],
    modelPickerEnabled: false,
  },
  {
    id: "sora-20250502",
    name: "Sora (2025-05-02)",
    vendor: "openai",
    family: "sora",
    kind: "video",
    contextWindow: 0,
    maxOutputTokens: 0,
    input: TEXT_IMAGE_VIDEO_INPUT,
    endpoints: [VIDEOS_ENDPOINT],
    modelPickerEnabled: false,
  },
  {
    id: "sora-2-20251006",
    name: "Sora 2",
    vendor: "openai",
    family: "sora",
    kind: "video",
    contextWindow: 0,
    maxOutputTokens: 0,
    input: TEXT_IMAGE_VIDEO_INPUT,
    endpoints: [VIDEOS_ENDPOINT],
    modelPickerEnabled: false,
  },
] satisfies Array<CloudGptModelDefinition>

function normalizeCloudGptModel(model: CloudGptModelDefinition): Model {
  const supportsVision = model.input.includes("image")
  const supportsStreaming = model.kind === "chat" || model.kind === "video"
  const isChatModel = model.kind === "chat"
  const toolCalls = model.toolCalls ?? isChatModel
  const modelPickerEnabled = model.modelPickerEnabled ?? isChatModel

  return {
    capabilities: {
      family: model.family,
      limits: {
        max_context_window_tokens: model.contextWindow,
        max_output_tokens: model.maxOutputTokens,
        max_prompt_tokens: model.contextWindow,
      },
      object: "model_capabilities",
      supports: {
        parallel_tool_calls: model.parallelToolCalls ?? toolCalls,
        reasoning_effort: model.reasoningEffort,
        streaming: supportsStreaming,
        structured_outputs: model.structuredOutputs,
        tool_calls: toolCalls,
        vision: supportsVision,
      },
      tokenizer: model.tokenizer ?? "o200k_base",
      type: model.kind,
    },
    id: model.id,
    model_picker_enabled: modelPickerEnabled,
    name: model.name,
    object: "model",
    preview: model.preview ?? false,
    supported_endpoints: [...model.endpoints],
    vendor: model.vendor,
    version: model.version ?? "cloudgpt",
  }
}

export function getModels(): ModelsResponse {
  return {
    object: "list",
    data: CLOUDGPT_MODEL_CATALOG.map((model) => normalizeCloudGptModel(model)),
  }
}

export type CloudGptChatProviderType = "openai-compatible" | "openai-responses"

const CLOUDGPT_ENDPOINT_BY_PROVIDER_TYPE: Record<
  CloudGptChatProviderType,
  string
> = {
  "openai-compatible": CHAT_COMPLETIONS_ENDPOINT,
  "openai-responses": RESPONSES_ENDPOINT,
}

// Resolves how a CloudGPT chat model should be reached, based on the
// endpoints it supports in cloudgpt_aoai.py. `preferredTypes` lets callers
// favor their native protocol when a model supports both.
export function getCloudGptModelProviderType(
  modelId: string,
  preferredTypes: Array<CloudGptChatProviderType> = [
    "openai-compatible",
    "openai-responses",
  ],
): CloudGptChatProviderType | undefined {
  const model = CLOUDGPT_MODEL_CATALOG.find((entry) => entry.id === modelId)
  if (!model || model.kind !== "chat") {
    return undefined
  }

  for (const providerType of preferredTypes) {
    if (
      model.endpoints.includes(CLOUDGPT_ENDPOINT_BY_PROVIDER_TYPE[providerType])
    ) {
      return providerType
    }
  }

  return undefined
}
